name = "business-ideas-generator"
type = "webpack"
account_id = "" # You'll get this from Cloudflare
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2024-03-26"
compatibility_flags = ["nodejs_compat"]
main = "workers-site/index.js"

[site]
bucket = "./frontend"
pages_build_output_dir = "dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[logs]
tail = true

[build]
command = "npm install && npm run build"

