name = "business-ideas-generator"
workers_dev = true
compatibility_date = "2024-03-26"
main = "workers-site/index.js"

[site]
bucket = "./frontend"
pages_build_output_dir = "dist"

[env.production]
vars = { ENVIRONMENT = "production" }

[logs]
tail = true

[build]
command = "npm install && npm run build"

